"""
Handles reading and writing CSV data for the Budget Buddy application.

DO NOT EDIT THIS FILE.
"""

import csv
import os

BUDGET_FIELDNAMES = ["month", "income_source", "income", "category", "planned_amount"]
EXPENSE_FIELDNAMES = ["date", "month", "category", "description", "amount"]
BUDGET_FILENAME = "budget_data.csv"
EXPENSE_FILENAME = "expense_data.csv"


def load_budget_data(filename=BUDGET_FILENAME):
    """
    Loads all budget records from the given CSV file.

    Returns a list of dictionaries. If the file does not exist yet,
    an empty list is returned.
    """
    budget_entries = []

    if not os.path.exists(filename):
        return budget_entries

    with open(filename, mode="r", newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            row["income"] = float(row["income"])
            row["planned_amount"] = float(row["planned_amount"])
            budget_entries.append(row)

    return budget_entries


def save_budget_data(budget_entries, filename=BUDGET_FILENAME):
    """
    Saves the full list of budget records to the given CSV file.
    budget_entries: list of dictionaries matching BUDGET_FIELDNAMES
    """
    with open(filename, mode="w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=BUDGET_FIELDNAMES)
        writer.writeheader()
        for entry in budget_entries:
            writer.writerow(entry)


def load_expense_data(filename=EXPENSE_FILENAME):
    """
    Loads all expense records from the given CSV file.

    Returns a list of dictionaries. If the file does not exist yet,
    an empty list is returned.
    """
    expense_entries = []

    if not os.path.exists(filename):
        return expense_entries

    with open(filename, mode="r", newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            row["amount"] = float(row["amount"])
            expense_entries.append(row)

    return expense_entries


def save_expense_data(expense_entries, filename=EXPENSE_FILENAME):
    """
    Saves the full list of expense records to the given CSV file.
    This overwrites the existing file with the provided data.

    expense_entries: list of dictionaries matching EXPENSE_FIELDNAMES
    """
    with open(filename, mode="w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=EXPENSE_FIELDNAMES)
        writer.writeheader()
        for entry in expense_entries:
            writer.writerow(entry)


def add_expense(expense_entry, filename="expense_data.csv"):
    """
    Appends a single new expense record to the CSV file without
    rewriting the entire file. 

    expense_entry: a dictionary matching EXPENSE_FIELDNAMES
    """
    file_exists = os.path.exists(filename)

    with open(filename, mode="a", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=EXPENSE_FIELDNAMES)
        if not file_exists:
            writer.writeheader()
        writer.writerow(expense_entry)
